# Generated by Django 5.1.5 on 2025-01-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDakar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description_poste', models.TextField(blank=True, null=True)),
                ('profil_recherche', models.TextField(blank=True, null=True)),
                ('entreprise', models.CharField(max_length=200)),
                ('localisation', models.CharField(max_length=200)),
                ('type_contrat', models.CharField(max_length=50)),
                ('niveau_etude', models.CharField(blank=True, max_length=200, null=True)),
                ('niveau_experience', models.CharField(blank=True, max_length=200, null=True)),
                ('competences', models.TextField(blank=True, null=True)),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('site_internet', models.URLField(blank=True, max_length=255, null=True)),
                ('description_entreprise', models.TextField(blank=True, null=True)),
                ('date_publication', models.DateTimeField(blank=True, null=True)),
                ('lien_offre', models.URLField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='EmploiSenegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description_poste', models.TextField()),
                ('profil_recherche', models.TextField(default='')),
                ('entreprise', models.CharField(max_length=100)),
                ('localisation', models.CharField(max_length=100)),
                ('lien_offre', models.URLField()),
                ('source', models.CharField(default='emploisenegal.com', max_length=100)),
                ('date_publication', models.DateField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('niveau_experience', models.CharField(blank=True, max_length=100)),
                ('type_contrat', models.CharField(blank=True, max_length=100)),
                ('competences', models.CharField(blank=True, max_length=200)),
                ('secteur_activite', models.CharField(blank=True, max_length=200, null=True)),
                ('site_internet', models.URLField(blank=True, null=True)),
                ('description_entreprise', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_publication'],
            },
        ),
    ]
