# Generated by Django 5.1.5 on 2025-01-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_emploi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emploidakar',
            name='competences',
        ),
        migrations.RemoveField(
            model_name='emploidakar',
            name='description_entreprise',
        ),
        migrations.RemoveField(
            model_name='emploidakar',
            name='niveau_etude',
        ),
        migrations.RemoveField(
            model_name='emploidakar',
            name='niveau_experience',
        ),
        migrations.RemoveField(
            model_name='emploidakar',
            name='secteur_activite',
        ),
        migrations.RemoveField(
            model_name='emploidakar',
            name='site_internet',
        ),
    ]
