# Generated by Django 4.2.18 on 2025-01-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_emploi', '0002_remove_emploidakar_competences_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenjobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('localisation', models.CharField(max_length=100)),
                ('type_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('date_publication', models.DateField()),
                ('date_expiration', models.DateField()),
                ('lien_offre', models.URLField(max_length=500)),
                ('description_poste', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'senjob',
                'ordering': ['-date_publication'],
            },
        ),
    ]
